### ISSUE TITLE
Document : RHEL related subcription

### ISSUE THREAD

**Issue by boopalans** [pndaproject/pnda#119]
Need to add RHEL subscription  details in the document section.

**Comment by trsmith2** [comment]
PNDA doesn't supply a subscription and in terms of how to obtain one we always defer to the authoritative source, being the RHEL documentation. Could you please explain what isn't clear beyond these two points?

**Comment by jgarnier** [comment]
RHEL subscription is not needed for AWS as this is already included, but for OpenStack, everything is describe in the [pnda-dib-elements](https://github.com/pndaproject/pnda-dib-elements#rhel-configuration-file) repo as you can see
