### ISSUE TITLE
Contribute a new page in this wiki about how to contribute to this wiki.

### ISSUE THREAD

**Issue by stephanesan** [pndaproject/pnda#124]
Wite up a page in this wiki about how to contribute to this wiki without being a member of the official project contributors.

**Comment by stephanesan** [comment]
A resolution proposal for this issue is available at:
- repo: https://github.com/stephanesan/pnda.wiki.git 
- branch: patch-124

**Comment by trsmith2** [comment]
Merged - thanks!
