### ISSUE TITLE
install - logstash not taking into account proxy

### ISSUE THREAD

**Issue by mathieuduperre** [pndaproject/pnda#155]
Found this while installing. If behind a proxy:

Error:

When create_mirror_misc.sh runs, it will download:

https://artifacts.elastic.co/downloads/logstash/logstash-5.2.2.tar.gz

which will unpack and try to run this script:

/tmp/logstash-5.2.2/bin/logstash-plugin

This script will not take into account the proxy settings. 

Workaround:

vi /tmp/logstash-5.2.2/bin/logstash-plugin

#edit the line below to add the proxy and port settings

export JRUBY_OPTS="$JRUBY_OPTS -J-Dhttp.proxyHost=proxy.esl.cisco.com -J-Dhttp.proxyPort=80 -J-XX:+TieredCompilation -J-XX:TieredStopAtLevel=1 -J-noverify -X-C -Xcompile.invokedynamic=false"

#edit create_mirror_misc.sh to comment out the curl and rm where you download and unpack logstash tarball

#make sure to remove those files as the script does not like to be run twice...

 rm -rf mirror-dist/mirror_misc/*

you should be able to run create_mirror_misc.sh from behind a proxy succesfully.

**Comment by stephanesan** [comment]
This [section](https://github.com/pndaproject/pnda-guide/blob/develop/provisioning/aws/MIRROR.md#configure-the-proxy-optional) in the guide explains how to set up the environment (including the JRUBY_OPTS). Did you encounter any problems with it?

**Comment by stephanesan** [comment]
Closing this one since there is no further information and guide improvement after doc review has already been merged.
