### ISSUE TITLE
Unable to build pnda on 2 different servers 

### ISSUE THREAD

**Issue by johnoloughlin** [pndaproject/pnda#54]
Steps taken
clone pnda
./install-build-tools.sh script
source set-pnda-env.sh
./build-pnda.sh RELEASE release/3.4

[INFO] Reading assembly descriptor: src/main/assembly/assembly.xml
[INFO] Building tar : /root/work/pnda/build/pnda-stage/platform-deployment-manager/api/target/deployment-manager-0.3.0.tar.gz
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 20.160s
[INFO] Finished at: Thu May 11 08:32:09 GMT+01:00 2017
[INFO] Final Memory: 14M/1216M
[INFO] ------------------------------------------------------------------------
Cloning into 'platform-console-backend'...
remote: Counting objects: 293, done.
remote: Total 293 (delta 0), reused 0 (delta 0), pack-reused 293
Receiving objects: 100% (293/293), 80.48 KiB | 0 bytes/s, done.
Resolving deltas: 100% (173/173), done.
Checking connectivity... done.
Note: checking out '3517f4a6b474209689433fefe2db83d4b81a2051'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

npm: Not Found
Please run the build dependency installer script
Build error
Please determine the reason for the error, correct and re-run

**Running npm in terminal **
root@silpixa00378251:~/work/pnda/build# npm

Usage: npm <command>

where <command> is one of:
    access, adduser, bin, bugs, c, cache, completion, config,
    ddp, dedupe, deprecate, dist-tag, docs, edit, explore, get,
    help, help-search, i, init, install, install-test, it, link,
    list, ln, login, logout, ls, outdated, owner, pack, ping,
    prefix, prune, publish, rb, rebuild, repo, restart, root,
    run, run-script, s, se, search, set, shrinkwrap, star,
    stars, start, stop, t, tag, team, test, tst, un, uninstall,
    unpublish, unstar, up, update, v, version, view, whoami

npm <cmd> -h     quick help on <cmd>
npm -l           display full usage info
npm help <term>  search for help on <term>
npm help npm     involved overview

Specify configs in the ini-formatted file:
    /root/.npmrc
or on the command line via: npm <command> --key value
Config info can be viewed via: npm help config

npm@3.10.10 /usr/lib/node_modules/npm

**Comment by johnoloughlin** [comment]
nodejs installs npm version npm@3.10.10
The build script in build/pnda-stage/platform-console-backend checks for 
echo -n "npm: "
NPM_VERSION=$(npm --version 2>&1)
if [[ ${NPM_VERSION} == "1.3"* ]] || [[ ${NPM_VERSION} == "3.5.2" ]]; then
    echo "OK"
else
    error
fi

**Comment by trsmith2** [comment]
Please sync your repository versions. For example if build release/3.4, get all the repos at this tag - pnda.git, pnda-heat-templates.git, pnda-aws-templates.git, etc - and make sure you're specifying release/3.4 as the branch version when you create PNDA.

**Comment by johnoloughlin** [comment]
The  ./build-pnda.sh RELEASE release/3.4 downloads the incorrect versions of the repos
I removed the pnda project and tried again.  
I ended up getting the same problem.
I am using the develop branch.
Am I going to need to download each repo manually or should the build script do this?


I have attached logs from the rerun (the install script worked correctly)
root@silpixa00378251:~/work/pnda/build# ./build-pnda.sh RELEASE release/3.4
git: OK                                                                    
Cloning into 'platform-deployment-manager'...                              
remote: Counting objects: 303, done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 303 (delta 1), reused 0 (delta 0), pack-reused 295
Receiving objects: 100% (303/303), 303.08 KiB | 224.00 KiB/s, done.
Resolving deltas: 100% (130/130), done.                            
Checking connectivity... done.                                     
Note: checking out '27cdfb864574e75ddeba9e29d9cbcd59e9a4620d'.     

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.     

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

Apache Maven 3.0.5: OK
Code quality: 10.00   
........................................................
----------------------------------------------------------------------
Ran 56 tests in 0.262s                                                

OK
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building deployment-manager 0.0.1-SNAPSHOT                              
[INFO] ------------------------------------------------------------------------
[INFO]                                                                         
[INFO] --- versions-maven-plugin:2.3:set (default-cli) @ deployment-manager ---
[INFO] Searching for local aggregator root...                                  
[INFO] Local aggregation root: /root/work/pnda/build/pnda-stage/platform-deployment-manager/api
[INFO] Processing change of com.cisco.pnda:deployment-manager:0.0.1-SNAPSHOT -> 0.3.0          
[INFO] Processing com.cisco.pnda:deployment-manager
[INFO]     Updating project com.cisco.pnda:deployment-manager
[INFO]         from version 0.0.1-SNAPSHOT to 0.3.0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.341s
[INFO] Finished at: Tue May 16 09:11:14 GMT+01:00 2017
[INFO] Final Memory: 20M/964M
[INFO] ------------------------------------------------------------------------
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building deployment-manager 0.3.0
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.4.1:clean (default-clean) @ deployment-manager ---
[INFO]
[INFO] --- maven-assembly-plugin:2.2-beta-5:single (make-assembly) @ deployment-manager ---
[INFO] Reading assembly descriptor: src/main/assembly/assembly.xml
[INFO] Building tar : /root/work/pnda/build/pnda-stage/platform-deployment-manager/api/target/deployment-manager-0.3.0.tar.gz
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.142s
[INFO] Finished at: Tue May 16 09:11:18 GMT+01:00 2017
[INFO] Final Memory: 16M/964M
[INFO] ------------------------------------------------------------------------
Cloning into 'platform-console-backend'...
remote: Counting objects: 298, done.
remote: Total 298 (delta 0), reused 0 (delta 0), pack-reused 298
Receiving objects: 100% (298/298), 80.94 KiB | 0 bytes/s, done.
Resolving deltas: 100% (177/177), done.
Checking connectivity... done.
Note: checking out '3517f4a6b474209689433fefe2db83d4b81a2051'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

npm: Not Found
Please run the build dependency installer script
Build error
Please determine the reason for the error, correct and re-run
root@silpixa00378251:~/work/pnda/build#

**Comment by trsmith2** [comment]
You need to sync your repository versions. For example if you are building release/3.4, get all the repos at this tag. This includes the pnda.git repository.

**Comment by johnoloughlin** [comment]
Removed project and started again
root@silpixa00378251:~/work/pnda/build# git status
HEAD detached at release/3.4

This will cause nodejs : Conflicts: npm (as the apt versions of nodejs have been updated for npm)
 
The version of the platform-console-backend that it pulls will only work with older versions of npm which is the same problem.

looking at the 3.4 release of
echo -n "npm: "
NPM_VERSION=$(npm --version 2>&1)
if [[ ${NPM_VERSION} == "1.3"* ]] || [[ ${NPM_VERSION} == "3.5.2" ]]; then
    echo "OK"
else
    error
fi 

if npm is 3.10.10 (which will be installed with nodjs by install script) the build will fail

**Comment by trsmith2** [comment]
The release/3.4 version of pnda.git doesn't install npm 3.10, you have that because you ran the develop version first.

**Comment by johnoloughlin** [comment]
You are correct.
reran instillation on new board and npm 3.5.2 was installed.

**Comment by boopalans** [comment]
I am new to the PNDA, trying to create build by following the document and facing issues while building. 
OS : Ubuntu 14.04 server.

1.  Ran the script create_mirror.sh. 
     Successfully completed and created the below dir stucture.
     drwxr-xr-x 2 root root  4096 Jun 27 12:07 mirror_anaconda
    drwxr-xr-x 2 root root  4096 Jun 27 12:06 mirror_cloudera
    drwxr-xr-x 2 root root 36864 Jun 27 12:02 mirror_deb
    drwxr-xr-x 2 root root  4096 Jun 27 12:06 mirror_misc
    drwxr-xr-x 4 root root  4096 Jun 27 12:09 mirror_python

2. Ran the script build/install-build-tools.sh 
    completed successfully.

3.  Ran the script build/build-pnda.sh RELEASE/3.4 
        Got NPM error. From the script looking for 3.5.2 but the installed version is 3.10.10. When trying to downgrade to 3.5.2 in Ubuntu 14.04 server, got error "Invalid version" 
       So fixed in the build-pnda,sh script, the NPM to 3.10.10.
       
        Then reran the build-pnda.sh again.

4. Then hitting issues with respect to Java version.
   The pnda-stage/gobblin/build.sh, checking against Java version 1.8.0_74. But the other dependency  scripts install the latest Java 1.8.0_131. 
   Modified pnda-stage/gobblin/build.sh  > Java version to 1.8.0_131 which is installed.

5. Rerunning the build-pnda.sh and hitting with the below issue
  
gobblin.metastore.DatabaseJobHistoryStoreV100Test.setUp FAILED
    java.lang.RuntimeException

15 tests completed, 1 failed, 10 skipped
:gobblin-metastore:test FAILED
Pass 2: Analyzing classes (39 / 193) - 19% complete
Pass 2: Analyzing classes (193 / 193) - 100% complete
Done with analysis

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':gobblin-metastore:test'.

The installed version is 3.10.10. So modified the script 


6. Apart from the above, there are 2 links which is not available.
  javadoc: warning - Error fetching URL: http://docs.guava-libraries.googlecode.com/git-history/v15.0/javadoc/
javadoc: warning - Error fetching URL: http://hadoop.apache.org/docs/r2.6.0-cdh5.9.0/api/

Can any one help here?  Am I missing any thing?
