### ISSUE TITLE
Issues while building PNDA RELEASE/3.4

### ISSUE THREAD

**Issue by boopalans** [pndaproject/pnda#69]
I am new to the PNDA, trying to create build by following the document and facing issues while building.
OS : Ubuntu 14.04 server.

    Ran the script create_mirror.sh.
    Successfully completed and created the below dir stucture.
    drwxr-xr-x 2 root root 4096 Jun 27 12:07 mirror_anaconda
    drwxr-xr-x 2 root root 4096 Jun 27 12:06 mirror_cloudera
    drwxr-xr-x 2 root root 36864 Jun 27 12:02 mirror_deb
    drwxr-xr-x 2 root root 4096 Jun 27 12:06 mirror_misc
    drwxr-xr-x 4 root root 4096 Jun 27 12:09 mirror_python

    Ran the script build/install-build-tools.sh
    completed successfully.

    Ran the script build/build-pnda.sh RELEASE/3.4
    Got NPM error. From the script looking for 3.5.2 but the installed version is 3.10.10. When trying to downgrade to 3.5.2 in Ubuntu 14.04 server, got error "Invalid version"
    So fixed in the build-pnda,sh script, the NPM to 3.10.10.

    Then reran the build-pnda.sh again.

    Then hitting issues with respect to Java version.
    The pnda-stage/gobblin/build.sh, checking against Java version 1.8.0_74. But the other dependency scripts install the latest Java 1.8.0_131.
    Modified pnda-stage/gobblin/build.sh > Java version to 1.8.0_131 which is installed.

    Rerunning the build-pnda.sh and hitting with the below issue

gobblin.metastore.DatabaseJobHistoryStoreV100Test.setUp FAILED
java.lang.RuntimeException

15 tests completed, 1 failed, 10 skipped
:gobblin-metastore:test FAILED
Pass 2: Analyzing classes (39 / 193) - 19% complete
Pass 2: Analyzing classes (193 / 193) - 100% complete
Done with analysis

FAILURE: Build failed with an exception.

    What went wrong:
    Execution failed for task ':gobblin-metastore:test'.

The installed version is 3.10.10. So modified the script

    Apart from the above, there are 2 links which is not available.
    javadoc: warning - Error fetching URL: http://docs.guava-libraries.googlecode.com/git-history/v15.0/javadoc/
    javadoc: warning - Error fetching URL: http://hadoop.apache.org/docs/r2.6.0-cdh5.9.0/api/

Can any one help here? Am I missing any thing?

**Comment by trsmith2** [comment]
Closing as current supported release is 3.5 and many of these issues have been fixed. Please re-raise if found in 3.5 or later.
